"use client";

import { useState, useEffect } from "react";
import styles from "./InnovativeSolutions.module.css";

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

// ── Types ─────────────────────────────────────────────────────────────────

interface InnovativeIdea {
  ideaName: string;
  description: string;
  whyRelevant: string;
  benefits: string[];
  risks: string[];
  applicability: string;
}

export interface InnovativeSolutionsResult {
  ideas: InnovativeIdea[];
  generatedAt: string;
  aiProvider: string;
  aiModel: string;
}

export interface InnovativeSolutionsSummary {
  topIdeas: Array<{ ideaName: string; description: string; whyRelevant: string }>;
}

interface Props {
  assessmentId: number;
  onResult?: (summary: InnovativeSolutionsSummary) => void;
  initialResult?: InnovativeSolutionsResult | null;
}

// ── Component ─────────────────────────────────────────────────────────────

export default function InnovativeSolutions({ assessmentId, onResult, initialResult }: Props) {
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">(
    () => (initialResult ? "done" : "idle")
  );
  const [result, setResult] = useState<InnovativeSolutionsResult | null>(() => initialResult ?? null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // Fire onResult once on mount if we were given cached data
  useEffect(() => {
    if (!initialResult || !onResult) return;
    onResult({
      topIdeas: initialResult.ideas.slice(0, 2).map(i => ({
        ideaName: i.ideaName,
        description: i.description,
        whyRelevant: i.whyRelevant,
      })),
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function generate() {
    setStatus("loading");
    setErrorMsg(null);
    try {
      const res = await fetch(
        `${BASE_PATH}/api/assessment/${assessmentId}/innovative-solutions`,
        { method: "POST" }
      );
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? `HTTP ${res.status}`);
      }
      const data: InnovativeSolutionsResult = await res.json();
      setResult(data);
      setStatus("done");
      if (onResult) {
        onResult({
          topIdeas: data.ideas.slice(0, 2).map(i => ({
            ideaName: i.ideaName,
            description: i.description,
            whyRelevant: i.whyRelevant,
          })),
        });
      }
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Request failed");
      setStatus("error");
    }
  }

  // ── Idle / prompt state ──────────────────────────────────────────────

  if (status === "idle") {
    return (
      <div className={styles.promptState}>
        <p className={styles.promptText}>
          Explore alternative approaches, implementation variations, and emerging architectural
          options related to the proposed solution. Results are exploratory only and do not
          alter the deterministic recommendation.
        </p>
        <button className={styles.generateButton} onClick={generate}>
          Generate Innovative Ideas
        </button>
      </div>
    );
  }

  if (status === "loading") {
    return (
      <div className={styles.loadingState}>
        <span className={styles.spinner} aria-hidden="true" />
        <span>Generating innovative ideas&hellip;</span>
      </div>
    );
  }

  if (status === "error") {
    return (
      <div className={styles.errorState}>
        <strong>Generation failed:</strong> {errorMsg}
        <button className={styles.retryButton} onClick={generate}>Retry</button>
      </div>
    );
  }

  if (!result || result.ideas.length === 0) {
    return (
      <div className={styles.errorState}>
        No ideas were returned. The AI may need more input context (business problem, drivers,
        or proposed solution) to generate relevant alternatives.
        <button className={styles.retryButton} onClick={generate}>Retry</button>
      </div>
    );
  }

  // ── Results ──────────────────────────────────────────────────────────

  return (
    <div className={styles.results}>
      <div className={styles.metaBar}>
        <span>Generated by <strong>{result.aiModel}</strong> via {result.aiProvider}</span>
        <span>{new Date(result.generatedAt).toLocaleString()}</span>
        <button className={styles.regenerateButton} onClick={generate}>Regenerate</button>
      </div>

      <div className={styles.disclaimer}>
        These ideas are exploratory and AI-generated. They are intended to expand architectural
        thinking, not to replace the deterministic recommendation or require action.
      </div>

      <div className={styles.ideaList}>
        {result.ideas.map((idea, i) => (
          <IdeaCard key={i} idea={idea} index={i} />
        ))}
      </div>
    </div>
  );
}

// ── Idea Card ─────────────────────────────────────────────────────────────

function IdeaCard({ idea, index }: { idea: InnovativeIdea; index: number }) {
  return (
    <div className={styles.ideaCard}>
      <div className={styles.ideaHeader}>
        <span className={styles.ideaNumber}>Idea {index + 1}</span>
        <span className={styles.ideaName}>{idea.ideaName}</span>
      </div>

      <div className={styles.ideaBody}>
        <div className={styles.ideaSection}>
          <span className={styles.ideaLabel}>Description</span>
          <p className={styles.ideaText}>{idea.description}</p>
        </div>

        <div className={styles.ideaSection}>
          <span className={styles.ideaLabel}>Why it may be relevant</span>
          <p className={styles.ideaText}>{idea.whyRelevant}</p>
        </div>

        <div className={styles.ideaColumns}>
          <div className={styles.ideaSection}>
            <span className={styles.ideaLabel}>Benefits</span>
            <ul className={styles.ideaBulletList}>
              {idea.benefits.map((b, j) => (
                <li key={j} className={styles.benefit}>{b}</li>
              ))}
            </ul>
          </div>

          <div className={styles.ideaSection}>
            <span className={styles.ideaLabel}>Risks / Tradeoffs</span>
            <ul className={styles.ideaBulletList}>
              {idea.risks.map((r, j) => (
                <li key={j} className={styles.risk}>{r}</li>
              ))}
            </ul>
          </div>
        </div>

        <div className={styles.ideaSection}>
          <span className={styles.ideaLabel}>Applicability to this context</span>
          <p className={`${styles.ideaText} ${styles.applicabilityText}`}>{idea.applicability}</p>
        </div>
      </div>
    </div>
  );
}
